version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install NPM modules
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  lint:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint
  build:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: yarn build
      - save_cache:
          paths:
            - dist
          key: v1-dist
  deploy:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dist
      - run:
          name: Setup NPM credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access=public
