name: Build core
on:
  push:
    paths:
      - packages/core/**
jobs:
  build:
    uses: ./.github/workflows/build-package.yml
    with:
      build-script: build:full
      directory: packages/core
