name: Build demo
on:
  push:
    paths:
      - packages/demo/**
jobs:
  build:
    uses: ./.github/workflows/build-package.yml
    with:
      build-script: build:full
      directory: packages/demo
