name: Build react-utils
on:
  push:
    paths:
      - packages/react-utils/**
jobs:
  build:
    uses: ./.github/workflows/build-package.yml
    with:
      build-script: build:full
      directory: packages/react-utils
