name: Core
run-name: ${{ github.ref_type == 'tag' && 'Publish' || 'Build' }} ${{ github.ref_name || 'core' }}
on:
  push:
    branches: '*'
    tags: core-*
    paths:
      - .github/workflows/*
      - packages/core/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      directory: packages/core

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      directory: packages/core
