name: Demo
run-name: Build demo
on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/*
      - packages/demo/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      package: demo
