name: publish-core
on:
  push:
    tags:
      - core-v**
jobs:
  publish-core-package:
    uses: ./.github/workflows/publish-package.yml
    with:
      build-script: build:full
      directory: packages/core
      package: "@athenajs/core"
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
      slackToken: ${{ secrets.SLACK_TOKEN }}
