name: publish-utils
on:
  push:
    tags:
      - utils-v**
jobs:
  publish-utils-package:
    uses: ./.github/workflows/publish-package.yml
    with:
      directory: packages/utils
      package: "@athenajs/utils"
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
      slackToken: ${{ secrets.SLACK_TOKEN }}
