name: Publish utils
run-name: Publish ${{ github.ref_name }}
on:
  push:
    tags:
      - utils-v**
jobs:
  publish:
    uses: ./.github/workflows/publish-package.yml
    with:
      directory: packages/utils
      package: "@athenajs/utils"
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
      slackToken: ${{ secrets.SLACK_TOKEN }}
