name: Publish react-utils
run-name: Publish ${{ github.ref_name }}
on:
  push:
    tags:
      - react-utils-v**
jobs:
  publish:
    uses: ./.github/workflows/publish-package.yml
    with:
      build-script: build:full
      directory: packages/react-utils
      package: "@athenajs/react-utils"
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
      slackToken: ${{ secrets.SLACK_TOKEN }}
