name: Publish @athenajs/core
on:
  push:
    tags:
      - core-v**
jobs:
  publish:
    uses: ./.github/workflows/publish-package.yml
    with:
      directory: packages/core
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
