name: React Utils
run-name: ${{ github.ref_type == 'tag' && 'Publish' || 'Build' }} ${{ github.ref_type == 'tag' && github.ref_name || 'react-utils' }}
on:
  push:
    branches: '*'
    tags: react-utils-*
    paths:
      - .github/workflows/*
      - packages/react-utils/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      directory: packages/react-utils

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      directory: packages/react-utils
