name: Utils
run-name: ${{ github.ref_type == 'tag' && 'Publish' || 'Build' }} ${{ github.ref_name || 'utils' }}
on:
  push:
    branches: '*'
    tags: utils-*
    paths:
      - .github/workflows/*
      - packages/utils/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      directory: packages/utils
      build-script: build

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      directory: packages/utils
      build-script: build
